version: '3'
services:
  api-matching:
    container_name: gamelancer-matching-api
    build: ./docker
    ports:
      - "8900:80"
    volumes:
      - .:/var/www/gamelancer-api
    links:
      - redis-matching
      - db-matching
    networks:
      - gamelancer-matching-network
  redis-matching:
    container_name: gamelancer-matching-redis
    image: "redis:alpine"
    ports:
      - "8979:6379"
    networks:
      - gamelancer-matching-network
  echo-server-matching:
    container_name: gamelancer-matching-echo-server
    image: "lagun4ik/laravel-echo-server"
    ports:
      - "8901:6001"
    volumes:
      - .:/app
    links:
      - redis-matching
      - api-matching
    networks:
      - gamelancer-matching-network
  db-matching:
    container_name: gamelancer-matching-db
    image: "mariadb:10.1.30"
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: gamelancer_matching
    ports:
      - "8906:3306"
    volumes:
      - db-matching:/var/lib/mysql
    networks:
      - gamelancer-matching-network

volumes:
  db-matching:

networks:
  gamelancer-matching-network:
    driver: bridge
